version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: 0.0.1

    ports:
      - "8000:8000"

    volumes:
      - ./:/bassoon:ro

    environment:
      BASSOON_PORTS_FILEPATH: /bassoon/ports.json
      BASSOON_HTTP_PORT: :8000

    restart: on-failure

